name: Clojure CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: DeLaGuardo/setup-graalvm@3.1
      with:
        graalvm-version: '21.0.0.java11'
    - uses: DeLaGuardo/setup-clojure@master
      with:
        lein: 2.9.8
    - name: Install modules
      run: cd http3; lein install
    - name: Run tests
      run: lein test
